# Generated by Django 4.1.7 on 2023-04-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
        ('player_rating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playerrating',
            name='unique_player_rating',
        ),
        migrations.RenameField(
            model_name='playerrating',
            old_name='user_id',
            new_name='player',
        ),
        migrations.AlterUniqueTogether(
            name='playerrating',
            unique_together={('ball_game', 'player')},
        ),
        migrations.AddConstraint(
            model_name='playerrating',
            constraint=models.UniqueConstraint(fields=('ball_game', 'player'), name='unique_player_rating'),
        ),
    ]
