# Generated by Django 4.2 on 2023-04-18 03:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_event', '0001_initial'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(
                    max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('game_event_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='game_event.gameevent')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player')),
            ],
        ),
    ]
