# Generated by Django 4.2 on 2023-04-21 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('court', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtBallGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_game', models.CharField(choices=[('Soccer', 'Soccer'),
                                                        ('Basketball', 'Basketball'),
                                                        ('Volleyball', 'Volleyball'),
                                                        ('Baseball', 'Baseball'),
                                                        ('Tennis', 'Tennis'),
                                                        ('Rugby', 'Rugby'),
                                                        ('Golf', 'Golf'),
                                                        ('Cricket', 'Cricket'),
                                                        ('Handball', 'Handball')],
                                               max_length=100)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='court.court')),
            ],
            options={
                'unique_together': {('court', 'ball_game')},
            },
        ),
    ]
