# Generated by Django 4.2 on 2023-04-17 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    primary_key=True,
                    serialize=False,
                    to=settings.AUTH_USER_MODEL)),
                ('birth_date', models.DateField()),
                ('favorite_ball_game', models.CharField(
                    choices=[('Soccer', 'Soccer'),
                             ('Basketball', 'Basketball'),
                             ('Volleyball', 'Volleyball'),
                             ('Baseball', 'Baseball'),
                             ('Tennis', 'Tennis'),
                             ('Rugby', 'Rugby'),
                             ('Golf', 'Golf'),
                             ('Cricket', 'Cricket'),
                             ('Handball', 'Handball')],
                    max_length=100)),
            ],
        ),
    ]
