# Generated by Django 4.2 on 2023-04-19 18:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('court', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('level_of_game', models.IntegerField(blank=True, choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'),
                                                                           (3, 'Three'), (4, 'Four'), (5, 'Five'),
                                                                           (6, 'Six'), (7, 'Seven'), (8, 'Eight'),
                                                                           (9, 'Nine'), (10, 'Ten')])),
                ('min_number_of_players', models.PositiveIntegerField()),
                ('max_number_of_players', models.PositiveIntegerField()),
                ('ball_game', models.CharField(choices=[('Soccer', 'Soccer'), ('Basketball', 'Basketball'),
                                                        ('Volleyball', 'Volleyball'), ('Baseball', 'Baseball'),
                                                        ('Tennis', 'Tennis'), ('Rugby', 'Rugby'), ('Golf', 'Golf'),
                                                        ('Cricket', 'Cricket'), ('Handball', 'Handball')],
                                               max_length=100,
                                               validators=[django.core.validators.MinLengthValidator(4)])),
                ('court_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='court.court')),
            ],
        ),
    ]
