# Generated by Django 4.2 on 2023-04-30 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(model_name='gameevent', old_name='court_id', new_name='court',),
    ]
