# Generated by Django 4.2 on 2023-05-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_event', '0002_rename_court_id_gameevent_court'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
