# Generated by Django 4.2 on 2023-04-19 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_event', '0001_initial'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEventPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_responsible', models.BooleanField(default=False)),
                ('game_event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                    to='game_event.gameevent')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player')),
            ],
            options={
                'unique_together': {('game_event_id', 'player_id')},
            },
        ),
    ]
