# Generated by Django 4.2 on 2023-05-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_event', '0002_rename_court_id_gameevent_court'),
        ('player', '0001_initial'),
        ('game_event_player', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameeventplayer',
            old_name='game_event_id',
            new_name='game_event',
        ),
        migrations.RenameField(
            model_name='gameeventplayer',
            old_name='player_id',
            new_name='player',
        ),
        migrations.AlterUniqueTogether(
            name='gameeventplayer',
            unique_together={('game_event', 'player')},
        ),
        migrations.AddConstraint(
            model_name='gameeventplayer',
            constraint=models.UniqueConstraint(fields=('game_event', 'player'), name='unique_game_event_player'),
        ),
    ]
